# This workflow will build and deploy Angular app to GitHub Pages

name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ "master" ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Angular animations
      run: npm install @angular/animations@^20.3.0
      
    - name: Build Angular app
      run: npm run build -- --base-href="/multiplication-table/"
      
    - name: List build output (debug)
      run: |
        ls -la dist/
        ls -la dist/multiplication-table/ || echo "multiplication-table folder not found"
        ls -la dist/multiplication-table/browser/ || echo "browser folder not found"
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './dist/multiplication-table/browser'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
